### ISSUE TITLE
Redirect Uris and Post Logout Redirect Uris is editable text

### ISSUE THREAD

**Issue by mperk** [skoruba/IdentityServer4.Admin#86]
Hi again :)
I have long redirectUri and logoutUri. I don't edit the texts. Only I can remove it and add again.
Can you make the texts is editable?

**Comment by skoruba** [comment]
Hi @mperk 

The Picker component is not designed to edit the selected items currently.

I will consider it, but maybe in the future.

I think, as a workaround - it's easy to copy and paste correct value, isn't it? :)

Thanks!

**Comment by mperk** [comment]
I can not copy/past. The area is cleaning when I click it.
Please, can you check the area? Unable to copy
Thank you for your interest.

**Comment by skoruba** [comment]
@mperk I will create this feature in this beta version, I will contact you. :)

**Comment by skoruba** [comment]
Currently is the Picker component modified for editing the selected items - the changes are available on dev branch.
Thanks for great point!

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!

**Comment by epoyraz** [comment]
@skoruba we can edit the redirect urls. but it doesn't persist the edited urls. 
After pressing on "save client" i still see my old redirect url

**Comment by skoruba** [comment]
Please, check latest version from master, there was a bug. 😊
